### ISSUE TITLE
HS32_ALU operation

### ISSUE THREAD

**Issue by atsh** [HomebrewSiliconClub/hs32core-rtl#1]
Shouldn't line 43 on cpu/hs32_alu.v be an OR operation?

            (i_op == `HS32A_AND) ? { i_fl[1], i_a & i_b } :
            (i_op == `HS32A_AND) ? { i_fl[1], i_a | i_b } :

**Comment by TheOneKevin** [comment]
Thank you for letting us know! It is indeed a bug and should not be there. Just curious, are you from the HSC slack group?

**Comment by atsh** [comment]
No, not from slack group. I am a PnR engineer. Found your project from efabless mpw-one. I am planning to use your rtl to learn synthesis using yosys

**Comment by TheOneKevin** [comment]
Wow! That's amazing, have fun then :D
